all the scripts have had a small addition to make them more verbose/self-explanatory in use

diff --git a/s/push-envs-github-secret b/s/push-envs-github-secret
--- a/s/push-envs-github-secret
+++ b/s/push-envs-github-secret
@@ -1,24 +1,26 @@
 #!/bin/bash
 
+set -v  # Enable verbose mode
+set -e  # Exit on error
+
 # scripts may need to be made executable on some platforms before they can be run
 # chmod +x <filename> is the command to do this on unixy systems
 
 ### IMPORTANT ###
 # you will need the `gh` (GitHub CLI) executable installed and configured on your system
 
-# Define the path to the .env file
+# Set variables
 env_file_path="envs/.env"
 repo="rcpch/rcpch-audit-engine"
 secret_name="ENVIRONMENT"
 
-
-# Check if the file exists
+# Check if the .env file exists
 if [ ! -f "$env_file_path" ]; then
     echo "File not found at $env_file_path!"
     exit 1
 fi
 
-# Base64 encode the file
+# Base64 encode the .env file contents
 encoded_content=$(base64 "$env_file_path")
 
 # Ask for confirmation
@@ -32,5 +34,10 @@ fi
 # Set the secret using GitHub CLI
 gh secret set "$secret_name" -b"$encoded_content" --repo "$repo"
 
-echo "Secret set successfully."
-
+# Check if the `gh` command was successful
+if [ $? -eq 0 ]; then
+    echo "Secret set successfully."
+else
+    echo "Failed to set the secret."
+    exit 1
+fi
